# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 727177365ab0874b760c5049ae82d2ee5805e50f7bf47f57000f7f0f432c9ced1fb8c8c0d5a78add8b7da9dc76139945de2dc36254129e0b92b451fd61ecc484

test:
  secret_key_base: f96e16ae6707b7fd6388503b5506f9439bc9c7c19ba2c1459bcf32c41a9fa23f961aedfc3668f7b585b6ea2a496c96dd43a31a55a001f38e44604ad6b866a7e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
